### ISSUE TITLE
Python library ready for publication

### ISSUE THREAD

**Issue by arlin** [phylotastic/phylotastic#203] opened 2018-05-17 15:36 UTC
6/8/2018	Python library. 

- [x] package is accessible
- [X] package auto-installs or installs per simple instructions
- [x] documentation matches functionality
   - [x] phylotastic_services.common_names
   - [x] phylotastic_services.extract_names
      - [x] phylotastic_services.extract_names_TEXT
      - [x] phylotastic_services.extract_names_URL
   - [x] phylotastic_services.get_info
      - [x] get_eolurls_species
      - [x] get_images_species
   - [x] phylotastic_services.get_species
      - [x] get_all_species
      - [x] get_country_species
      - [x] get_genome_species
   - [x] phylotastic_services.get_traits
      - [x] get_traits_ECOS
      - [x] get_traits_EOL
   - [x] phylotastic_services.get_tree
      - [x] get_tree_OpenTree
      - [x] get_tree_Phylomatic
   - [x] phylotastic_services.list_species
      - [x] list_species.List
      - [x] list_species.Species
      - [x] get_list_info
      - [x] insert_list_info
      - [x] remove_list_info
      - [x] update_list_data
      - [x] update_list_metadata
   - [x] phylotastic_services.resolve_names
      - [x] resolve_names_GNR
      - [x] resolve_names_OT
      - [x] resolve_names_iPlant
   - [x] phylotastic_services.study_tree
      - [x] compare_trees
      - [x] get_chronogram_tree
- [x] vignettes work

**Comment by arlin** [comment] 2018-07-19 01:46
Trying to install package following the instructions in README on github, I get 

>   Cannot fetch index base URL https://pypi.python.org/simple/
>  Could not find any downloads that satisfy the requirement itolapi (from phylotastic-services==0.1)
> Cleaning up...
> No distributions at all found for itolapi (from phylotastic-services==0.1)
> Storing debug log for failure in /Users/arlin/Library/Logs/pip.log

@abusalehmdtayeen can you comment on this?

**Comment by arlin** [comment] 2018-07-19 01:59
OK, I got the same kind of error when I tried to install sphinx in order to build the docs.  I'm new to Python.  This is probably a generic problem with my installation.  I will try to fix it. 

Meanwhile, why are the docs not included in the dist?

**Comment by abusalehmdtayeen** [comment] 2018-07-23 03:13
@arlin , The error you got was because of a dependency package which is outdated and we no longer use it. I have removed it and updated the distribution package. Now you would be able to install it successfully. 

You don't need to install and build the docs using sphinx.  Its already built and located in [docs/build/html](https://github.com/phylotastic/phylotastic_py/tree/master/docs/build/html) folder. Usually docs are not included in the distribution for python packages. Python distribution mainly contains the source files.

**Comment by arlin** [comment] 2018-08-04 00:24
@abusalehmdtayeen don't we need to explain to people that the way to read the docs is to point their browser to the local copy of build/html/index.html after first installing the package?  That is completely non-obvious to me.  It took me 10 minutes to figure this out.  I started with the github web site and found various PDF and html files that were not helpful

**Comment by arlin** [comment] 2018-08-21 15:53
docs are here:  http://phylo.cs.nmsu.edu:8000/py-modindex.html

**Comment by arlin** [comment] 2018-08-21 20:45
@abusalehmdtayeen, when I run the example for common name service, the "print result" command in Python gives

`
 {'status_code': 200, 'message': 'Success', 'result': [{'matched_names': [{'scientific_name': u'Bos taurus', 'common_name': u'domestic cattle (feral)', 'identifier': u'183838', 'source_info_url': 'https://www.itis.gov/ITISWebService/jsonservice/ITISService/getFullRecordFromTSN?tsn=183838'}], 'searched_name': 'domestic cattle'}, {'matched_names': [{'scientific_name': u'Balaenoptera musculus', 'common_name': u'Blue Whale', 'identifier': u'180528', 'source_info_url': 'https://www.itis.gov/ITISWebService/jsonservice/ITISService/getFullRecordFromTSN?tsn=180528'}], 'searched_name': 'blue whale'}], 'metadata': {'execution_time': '2.44', 'creation_time': '2018-08-21T16:38:59.493437', 'source_urls': ['https://www.itis.gov/ws_description.html']}}
`

Is this the way JSON is handled internally in Python.  If I try to validate this, it does not work,  because it uses single-quotes instead of double-quotes.  Also, python is putting a "u" before some strings to indicate that they are unicode.   Do I need to look at this with some Python json tools?

**Comment by abusalehmdtayeen** [comment] 2018-08-22 00:53
The result is a dump of python data structures. If you want, I can make it output a valid json by using an internal converter.

**Comment by arlin** [comment] 2018-08-30 15:02
@thanhnh-infinity, this is the ticket to review the python library.  

Thanks again for offering to do this!  We are looking for a very superficial review: just make sure that the examples in the docs work, and that the functions are sensible.  

The docs are here: http://phylo.cs.nmsu.edu:8000/py-modindex.html

The github repo is here: https://github.com/phylotastic/phylotastic_py

**Comment by thanhnh-infinity** [comment] 2018-09-01 05:48
@abusalehmdtayeen @arlin  : I started testing the Python library package and unfortunately I failed to install it from beginning. The problem is that I am using MacOS and Phylotastic Python Package required to create new folder 'ete3' in /System/Library/Python.framework... that is protected by macOS -  it means this action is not permitted by macOS - so the installation was failed. I guess this issue will be appeared for many users who have macOS

At the moment, I create a virtual machine that is running Ubuntu and try to install Phylotastic package again.

**Comment by thanhnh-infinity** [comment] 2018-09-01 06:04
@arlin @abusalehmdtayeen  : The installation is successful 100% on Ubuntu

**Comment by thanhnh-infinity** [comment] 2018-09-05 17:34
@arlin  @abusalehmdtayeen :

1. phylotastic_services.common_names works CORRECTLY as document - PASSED

![phylotastic_services.common_names.get_scientific_names.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/55c43708ca3a8110001749a7/125516c66e82c728ace21e0d46f89c832f8d97a89cfdb6409b4ef5863f4f24763a4aa0247d88ec26804c7a0c0a1c50fb141c3007afa0dc75e2ef6a29d93355bc8c381c66da2f51eee7d84aec45a82a994a80b3ee8f4ec7bd6e71b6dede1a3b4805188dfd0e3cf69c59d44ab41abf190af94a7c36a4643c6e469d147429686127adf9d651848366aca85d.png)

2. phylotastic_services.extract_names_TEXT  works well BUT I think the JSON message DOES NOT match with the documentation. There are some differences such as in my request I use taxonfinder,  in document the source_urls is taxonfinder, but in my test it is gnrd.globalnames.org and JSON message included gnrd_parameters also. - CHECKED

![Screen Shot 2018-09-05 at 10.49.12 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/55c43708ca3a8110001749a7/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b772a6454f66b7191a379ef0c2f58415e4cbc30254d58eeb9cb74fce36f34985619e8d4680d71c43a44ffecd34aee54bf768b4f81b4ef831ac5fa2137a5dad11b61435c52dcbd4f3fb2984cc259f348e74c53a2123061e270326e0a.png)

3. phylotastic_services.extract_names.extract_names_URL works CORRECTLY as document - PASSED

![Screen Shot 2018-09-05 at 10.52.26 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/55c43708ca3a8110001749a7/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b772a6454f66b7191a379ef0c2e53415d48bc30254d58eeb9cb74fce36f34985619e8d4680d71c43a44ffecd34aee54bf768b4f81b4ef831ac5fa2137a5dad11b61435c52dcbd4f3fb29842c259f348e74c53a2103364e272356e0a.png)

4. phylotastic_services.get_info.get_eolurls_species FAILED

![Screen Shot 2018-09-05 at 10.53.56 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/55c43708ca3a8110001749a7/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b772a6454f66b7191a379ef0c2e52415a48bc30254d58eeb9cb74fce36f34985619e8d4680d71c43a44ffecd34aee54bf768b4f81b4ef831ac5fa2137a5dad11b61435c52dcbd4f3fb29843c259f348e74c53a2173f65e073326e0a.png)

5. phylotastic_services.get_info.get_images_species FAILED

![Screen Shot 2018-09-05 at 10.55.34 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/55c43708ca3a8110001749a7/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b772a6454f66b7191a379ef0c2e54415c4abc30254d58eeb9cb74fce36f34985619e8d4680d71c43a44ffecd34aee54bf768b4f81b4ef831ac5fa2137a5dad11b61435c52dcbd4f3fb2984cc259f348e74c53a2163365e3723e6e0a.png)

6. phylotastic_services.get_species.get_all_species  works CORRECTLY as document - PASSED

![Screen Shot 2018-09-05 at 10.57.27 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/55c43708ca3a8110001749a7/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b772a6454f66b7191a379ef0c2e56415d49bc30254d58eeb9cb74fce36f34985619e8d4680d71c43a44ffecd34aee54bf768b4f81b4ef831ac5fa2137a5dad11b61435c52dcbd4f3fb2984cc259f348e74c53a2153e60e4703e6e0a.png)

7. phylotastic_services.get_species.get_country_species works CORRECTLY as document - PASSED

![Screen Shot 2018-09-05 at 10.59.00 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/55c43708ca3a8110001749a7/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b772a6454f66b7191a379ef0c2e58415f4ebc30254d58eeb9cb74fce36f34985619e8d4680d71c43a44ffecd34aee54bf768b4f81b4ef831ac5fa2137a5dad11b61435c52dcbd4f3fb29b4ac259f348e74c53a2143e60ef77326e0a.png)

8. phylotastic_services.get_species.get_genome_species works WELL But, the species in my test is different from in documentation. There are 7 names and the difference is "Puma concoler" which is existed on my test by does not include in documentation. -- CHECKED

![Screen Shot 2018-09-05 at 11.02.10 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/55c43708ca3a8110001749a7/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b772a6454f66b7191a379ee0c2b53415e4ebc30254d58eeb9cb74fce36f34985619e8d4680d71c43a44ffecd34aee54bf768b4f81b4ef831ac5fa2137a5dad11b61435c52dcbd4f3fb29b4bc259f348e74c53a21a3163e772326e0a.png)

9. phylotastic_services.get_traits.get_traits_ECOS works CORRECTLY as document -- PASSED

![Screen Shot 2018-09-05 at 11.04.01 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/55c43708ca3a8110001749a7/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b772a6454f66b7191a379ee0c2b55415f4fbc30254d58eeb9cb74fce36f34985619e8d4680d71c43a44ffecd34aee54bf768b4f81b4ef831ac5fa2137a5dad11b61435c52dcbd4f3fb29b4ac259f348e74c53a3133060e4723e6e0a.png)

10. phylotastic_services.get_traits.get_traits_EOL  FAILED

![Screen Shot 2018-09-05 at 11.05.28 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/55c43708ca3a8110001749a7/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b772a6454f66b7191a379ee0c2b54415d46bc30254d58eeb9cb74fce36f34985619e8d4680d71c43a44ffecd34aee54bf768b4f81b4ef831ac5fa2137a5dad11b61435c52dcbd4f3fb29843c259f348e74c53a3123263e670316e0a.png)

11. phylotastic_services.get_tree.get_tree_OpenTree FAILED - It takes me very long time but does not response anything

12. phylotastic_services.get_tree.get_tree_Phylomatic works CORRECTLY as document - PASSED

![Screen Shot 2018-09-05 at 11.10.29 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/55c43708ca3a8110001749a7/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b772a6454f66b7191a379ee0c2a51415d47bc30254d58eeb9cb74fce36f34985619e8d4680d71c43a44ffecd34aee54bf768b4f81b4ef831ac5fa2137a5dad11b61435c52dcbd4f3fb29843c259f348e74c53a317336ae477346e0a.png)

13. phylotastic_services.list_species.List  FAILED

![Screen Shot 2018-09-05 at 11.12.38 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/55c43708ca3a8110001749a7/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b772a6454f66b7191a379ee0c2a53415c46bc30254d58eeb9cb74fce36f34985619e8d4680d71c43a44ffecd34aee54bf768b4f81b4ef831ac5fa2137a5dad11b61435c52dcbd4f3fb29b4bc259f348e74c53a3163e66e6703e6e0a.png)

14. phylotastic_services.list_species.Species FAILED

![Screen Shot 2018-09-05 at 11.13.42 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/55c43708ca3a8110001749a7/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b772a6454f66b7191a379ee0c2a52415b4cbc30254d58eeb9cb74fce36f34985619e8d4680d71c43a44ffecd34aee54bf768b4f81b4ef831ac5fa2137a5dad11b61435c52dcbd4f3fb29b4bc259f348e74c53a3153360e5763f6e0a.png)

15. 
phylotastic_services.list_species.get_list_info  FAILED too, because cannot insert list so cannot get list

16. phylotastic_services.list_species.insert_list_info FAILED

![Screen Shot 2018-09-05 at 11.16.43 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/55c43708ca3a8110001749a7/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b772a6454f66b7191a379ee0c2a57415b4dbc30254d58eeb9cb74fce36f34985619e8d4680d71c43a44ffecd34aee54bf768b4f81b4ef831ac5fa2137a5dad11b61435c52dcbd4f3fb29843c259f348e74c53a31b3765ee70346e0a.png)

17. phylotastic_services.list_species.remove_list_info FAILED

18. phylotastic_services.list_species.update_list_data FAILED

19. phylotastic_services.list_species.update_list_metadata FAILED

20. phylotastic_services.resolve_names.resolve_names_GNR works CORRECTLY as document -- PASSED

![Screen Shot 2018-09-05 at 11.19.40 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/55c43708ca3a8110001749a7/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b772a6454f66b7191a379ee0c2a58415b4ebc30254d58eeb9cb74fce36f34985619e8d4680d71c43a44ffecd34aee54bf768b4f81b4ef831ac5fa2137a5dad11b61435c52dcbd4f3fb2984cc259f348e74c53a31a3f63e674376e0a.png)

21. phylotastic_services.resolve_names.resolve_names_OT works CORRECTLY as document -- PASSED

![Screen Shot 2018-09-05 at 11.21.03 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/55c43708ca3a8110001749a7/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b772a6454f66b7191a379ee0c2950415f4dbc30254d58eeb9cb74fce36f34985619e8d4680d71c43a44ffecd34aee54bf768b4f81b4ef831ac5fa2137a5dad11b61435c52dcbd4f3fb2984cc259f348e74c53ac133f60e471346e0a.png)

22. phylotastic_services.resolve_names.resolve_names_iPlant works CORRECTLY as document -- PASSED

![Screen Shot 2018-09-05 at 11.22.07 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/55c43708ca3a8110001749a7/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b772a6454f66b7191a379ee0c2953415f49bc30254d58eeb9cb74fce36f34985619e8d4680d71c43a44ffecd34aee54bf768b4f81b4ef831ac5fa2137a5dad11b61435c52dcbd4f3fb29842c259f348e74c53ac123367ee7e326e0a.png)

23. phylotastic_services.study_tree.compare_trees works CORRECTLY as document -- PASSED

![Screen Shot 2018-09-05 at 11.23.20 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/55c43708ca3a8110001749a7/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b772a6454f66b7191a379ee0c2952415d4ebc30254d58eeb9cb74fce36f34985619e8d4680d71c43a44ffecd34aee54bf768b4f81b4ef831ac5fa2137a5dad11b61435c52dcbd4f3fb2984cc259f348e74c53ac11356be070306e0a.png)

24. phylotastic_services.study_tree.get_chronogram_tree FAILED - It takes too long time and does not response anything

**Comment by abusalehmdtayeen** [comment] 2018-09-06 00:59
@thanhnh-infinity , There were mainly two problems for which you got these errors.

i) A config file was missing in the source distribution. This file has API keys which are used in the EOL related services. I have added this file to the distribution.
ii) For the list species methods, I think you directly used the examples to test. But you need to use your own access token to test these examples. The access token in the doc is a dummy string which will not work. Also, for some examples you need to import the appropriate class. This part was missing in the doc. So I have added it. 

I think you should uninstall your current package, download the latest distribution from github and try those examples again. It should work now.

**Comment by thanhnh-infinity** [comment] 2018-09-06 14:43
@abusalehmdtayeen : OK, Abu. I will re-test again and let you know the result. Thank you

**Comment by thanhnh-infinity** [comment] 2018-09-09 18:50
@arlin  @abusalehmdtayeen :

1. phylotastic_services.common_names works CORRECTLY as document - PASSED

2. phylotastic_services.extract_names_TEXT  -- PASSED

3. phylotastic_services.extract_names.extract_names_URL works CORRECTLY as document - PASSED

4. phylotastic_services.get_info.get_eolurls_species -- PASSED

5. phylotastic_services.get_info.get_images_species -- PASSED

6. phylotastic_services.get_species.get_all_species  works CORRECTLY as document - PASSED

7. phylotastic_services.get_species.get_country_species works CORRECTLY as document - PASSED

8. phylotastic_services.get_species.get_genome_species works WELL  -- PASSED

9. phylotastic_services.get_traits.get_traits_ECOS works CORRECTLY as document -- PASSED

10. phylotastic_services.get_traits.get_traits_EOL  -- PASSED

11. phylotastic_services.get_tree.get_tree_OpenTree  -- PASSED

12. phylotastic_services.get_tree.get_tree_Phylomatic works CORRECTLY as document - PASSED

13. phylotastic_services.list_species.List  -- PASSED

14. phylotastic_services.list_species.Species -- PASSED


15. phylotastic_services.list_species.get_list_info  -- PASSED

16. phylotastic_services.list_species.insert_list_info -- PASSED

17. phylotastic_services.list_species.remove_list_info -- PASSED

18. phylotastic_services.list_species.update_list_data -- PASSED

19. phylotastic_services.list_species.update_list_metadata -- PASSED

20. phylotastic_services.resolve_names.resolve_names_GNR works CORRECTLY as document -- PASSED

21. phylotastic_services.resolve_names.resolve_names_OT works CORRECTLY as document -- PASSED

22. phylotastic_services.resolve_names.resolve_names_iPlant works CORRECTLY as document -- PASSED

23. phylotastic_services.study_tree.compare_trees works CORRECTLY as document -- PASSED

24. phylotastic_services.study_tree.get_chronogram_tree -- PASSED

**Comment by thanhnh-infinity** [comment] 2018-09-09 18:51
@arlin @abusalehmdtayeen : after Abu made a fix for Phylotastic library, I re-tested again and all comands are passed

**Comment by arlin** [comment] 2018-09-09 21:53
@thanhnh-infinity thanks so much for doing all this work!  If you think this is done, please close the issue.

**Comment by thanhnh-infinity** [comment] 2018-09-09 23:32
@arlin . Yes, I will close this issue

**Closed by thanhnh-infinity** 2018-09-09 23:32 UTC
Labels: in progress
